### PR TITLE
Use a transparent title bar for Find & Replace window

### PR DESCRIPTION
**Pull request by kra-mo**
|Before|After|
|-|-|
|Screenshot 2024-12-17 at 23 10 54|Screenshot 2024-12-17 at 23 10 33|

### CODE REVIEW

**Comment by 1024jp** [comment]
The current design is intentional, so this pull request will not be accepted.

**Comment by kra-mo** [comment]
Okay. Can I ask why the title bar is separate? It looks a bit dated.

**Comment by 1024jp** [comment]
I’ve actually considered making the same change multiple times before, primarily for aesthetic reasons.
However, then I always came across the conclusion that there’s no valid reason to omit the separator.
The separator serves a visual purpose, separating the titlebar from the content area of the window.
For example, only the titlebar part allows the user to grab the window and drag it.
We shouldn’t alter the standard design merely because it appears “cool.”

Moreover, the titlebar separator in find panels is still alive.
For instance, the find panel in Pages also uses the separator.

Screenshot 2024-12-18 at 23 54 41

**Comment by kra-mo** [comment]
As long as the title bar is there, I understand, and I have also looked at the Pages example.

I think that the pattern of a titlebar like this in general is a holdover from earlier days and is not really consistent with newer patterns though.

Two options that could be a bit more modern is either
1. Not having a title at all, just retaining the window controls, and making the whole window draggable. This would be a fairly simple change and I could work on it if you agree.
2. Having a bar at the top like TextEdit, Safari, Terminal, Notes, etc.

For option 1, you could also have a custom close button, like many modern windows/dialogs that cannot be minimized or resized. Something like this:
image

What do you think?

In general, I think CotEditor is a really nice app and I would be happy to contribute more to the project :)

**Comment by kra-mo** [comment]
It’s not just because it’s cool, it is a more modern pattern used across the OS for good reason. Titles often don’t communicate a lot of useful info, so omitting them reduces visual noise, and yes, by extension makes the UI sleeker. I don’t think it would have any real drawbacks, people are used to this paradigm too, now more than ever. And the benefit is simplifying the app a bit, which I think is worth it.

Making empty space in the window draggable all-around is also a benefit.

**Comment by kra-mo** [comment]
And I do understand if you want to follow patterns from Apple software, eg. Pages. But on its own, I think there are small deviations that could be made that go a long way :)

**Comment by 1024jp** [comment]
The　CotEditor project has its own policies.
I'll change it when Apple changes their design philosophy.

If you have another idea, please do it on your apps.

**Comment by kra-mo** [comment]
Alright, I understand.

So the design philosophy of the project is to base all components off of preexisting Apple software?

**Comment by kra-mo** [comment]
For the record, I am completely fine with following whatever philosophy the project adheres to ^^

But I would like to know what direction the project plans to go in, since I would like to contribute more. Is there a place I can learn more?

**Comment by 1024jp** [comment]
This project is open-source, but it’s actually maintained solely by me.
Therefore, it lacks written rules; everything is in my head.

However, I’ll outline the fundamental policies of this project in the README later, as they may be useful for users.

**Comment by kra-mo** [comment]
Thanks ^^

In the mean time, are there any "good first" issues I could maybe pick up?

**Comment by 1024jp** [comment]
The CotEditor project does not call for active contributions of additional features from others.

**Pull request closed without merging**
