### PR TITLE
zh-Hant localization.

### PR DESCRIPTION
**Pull request by ShikiSuen**
To save some time, this PR is created **as a derivative work based on @onevcat 's zh-Hans localization**.

OpenCC is used for auto-conversion (zh-Hans to zh-Hant-TW).
However, I found that some words are not auto-converted correctly and fixed them manually.

At least, this PR is helpful to those people who born language is Traditional Chinese and can't understand Simplified Chinese glyphs. If further issues are found, we can use further PRs to fix them.

--------
このPRは OnevCat の簡体中国語翻訳に基づいてから作ったものである。
OpenCCで「zh-Hans」から「zh-Hant-TW」への自動転換をしましたが、転換し間違った単語は多少見つけたため直しました。
少なくとも、簡体中国語の簡体字を読みにくい人たちに甲斐のあるPRだと拙者の愚見です。
今後他の問題箇所を発見した場合、別のPRで直しましょう。

### CODE REVIEW

**Comment by 1024jp** [comment]
Looks nice! thank you. It seems we need to improve them to use more macOS-favored expressions. But, in general, I suppose it is already to merge. We can do such things after the merge.

By adding a new localization, we ask for continuous maintenance for future updates (ref. [Submitting a new localization -CONTRIBUTING.md](https://github.com/coteditor/CotEditor/blob/develop/CONTRIBUTING.md#submitting-a-new-localization)). May I ask you also to be the maintainer for future zh-Hant localization? When CotEditor has new strings to be localized, I'll call localization maintainers by creating an issue, just like #1250. This kind of update can happen normally about once per few months.

**Comment by 1024jp** [comment]
> It seems we need to improve them to use more macOS-favored expressions.

FYI, the website https://applelocalization.com/macos helps a lot by localizing macOS apps. This page enables you to search how Apple localizes the terms in their applications/frameworks in different languages.

**Comment by ShikiSuen** [comment]
@1024jp Although I am OK to join the maintainer for future zh-Hant localization, I also agree with further maintenances pull-requested  from other volunteers in case of having possible unavoidable access problems to GitHub. (I live in Shandong and I have to use virtual private network to access GitHub. Email communication is fine as long as you feel okay to share localization files through emails in such extreme circumstances).

By the way, the built-in Chinese translation used in macOS (whether zh-Hans or zh-Hant) is somehow "out-of-sense" (非常識) comparing to the nomenclature used by Microsoft. Not like Japan and Anglo-Saxon countries, Mainland China market was dominated by Windows for a really long time. The population of macOS is only due to the needs of developing apps for Apple devices. This is the reason why users in Mainland China market is generally get used to Microsoft nomenclatures. In Traditional Chinese market (HK, Taiwan, Macau, etc.), I assume the situation is similar.

OpenCC by default uses Microsoft nomenclatures with few exceptions like how the word "font" gets translated in Traditional Chinese.

Considering my schedule, I'll find some time to sync the expressions used in "applelocalization.com" to this repo in a future PR. Also, since I have no way to compile this repository on my computers, I would like to see how the current commit looks in CotEditor GUI.

**Comment by 1024jp** [comment]
@ShikiSuen Thank you for the reply, for accepting being the maintainer, and for describing the situation.

But before that, just after I merged the PR, I realized that there are some missing files to be localized (This is my fault. Sorry.). Could you also localize the followings?
- Localizable.strings
- InfoPlist.strings
- ServicesMenu.strings
- Unicode.strings

First copy those files from `en-GB.lproj` (or whatever you like) to `zh-Hant.lproj` and use them as the template.


> Although I am OK to join the maintainer for future zh-Hant localization, I also agree with further maintenances pull-requested from other volunteers in case of having possible unavoidable access problems to GitHub.

Ok, I understood. Some of the localization maintainers prefer sending emails over PRs on GitHub. So it is ok. In addition, if there is difficulty accessing you for some reason, I'll look for another person (or service) who can localize such updated strings to zh-Hant.

> By the way, the built-in Chinese translation used in macOS (whether zh-Hans or zh-Hant) is somehow "out-of-sense" (非常識) comparing to the nomenclature used by Microsoft. Not like Japan and Anglo-Saxon countries

Thank you also for sharing the situation of Chinese localization on Mac. I did not know that. In general, CotEditor aims to behave in the native Mac application manner as much as possible. From that point of view, we recommend using the terms that appear in other Apple applications. However, if it is totally wrong or something strange, prioritize other expressions that sound more natural.

**Pull request merged**
