### PR TITLE
Add Korean Localization

### PR DESCRIPTION
**Pull request by stonechoe**

### CODE REVIEW

**Comment by 1024jp** [comment]
Thank you for your contribution!
Are you still working on it?

I have quickly reviewed your commit and found that there are still a lot of strings that need to be localized. For instance:

- Localizable.xcstrings
- Document.xcstrings
- Intents.xcstrigns
- ThemeEditor.xcstrigns
- TextFind.xcstrings
- MultipleReplace.xcstrings
- RegexReference.xcstrings
- etc. 

In addition, it seems you use `“` and `”` for quotation marks in Korean. However, Apple seems to use `‘` and `’` expect for quotations of actual conversation. Please check how Apple translates such symbols and follow their manner.

The CotEditor project accepts only the localization 100% localized. So, please localize the remaining strings and 
let me know when you are finished. Then I'll review it again in detail.

While I am waiting for it to be finished, I’d like to confirm several questions I ask every contributor who commits the first localization:

- Have you read the [Localizations section in the CONTRIBUTING.md](https://github.com/coteditor/CotEditor/blob/main/CONTRIBUTING.md#localizations)? It summarizes the information for contributing to CotEditor localization, especially about quality control. Please follow the descriptions there.
- As described in the CONTRIBUTING.md, the CotEditor project currently only accepts new localizations whose provider can maintain them after that. So, let me know if you intend to be a localization maintainer as well.

**Comment by stonechoe** [comment]
Hi! 😃

I've revised the localization and translated all the text in `Storyboards` and `Localizables` under `Resources` (please let me know if this is not the case).

As you mentioned, I have also corrected the quotation marks, and adjusted some terms using the official translation terms as outlined in `CONTRIBUTING.MD`.

I intend to continue maintaining it as a localization maintainer in the future.

Thank you!

**Review by 1024jp — APPROVED** [review]

**Comment by 1024jp** [comment]
Thank you! The addition will be shipped with CotEditor 5.0.0 which will be released this autumn.

**Comment by 1024jp** [comment]
Oops, I missed some strings.
(They are hard to find. I need to update CONTRIBUTING.md to add more description.)

Could you localize the following lines just by replying to this thread?

```c
// encoding name for UTF-8 with BOM (%@ is the system localized name for UTF-8)
"%@ with BOM" = "%@ with BOM";

// label for the Unicode variation selector that forces to draw the character in the emoji style
"Emoji Style" = "Emoji Style";
"Text Style" = "Text Style";

// label for Unicode emoji modifier applying the skin tone to the character
"Skin Tone I-II" = "Skin Tone I-II";
"Skin Tone III" = "Skin Tone III";

// label for general Unicode variation selectors
"Variant" = "Variant";
```

**Comment by stonechoe** [comment]
Here it is:
```c
"%@ with BOM" = "%@ (BOM)";
"Emoji Style" = "이모티콘 스타일";
"Text Style" = "텍스트 스타일";
"Skin Tone I-II" = "피부 색 I-II";
"Skin Tone III" = "피부 색 III"; 
"Variant" = "변형";
> ```

**Comment by 1024jp** [comment]
Perfect! Thank you.

**Pull request merged**
