### PR TITLE
Update Turkish translations

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Review by 1024jp — APPROVED** [review]

**Comment by 1024jp** [comment]
Thank you!

**Comment by bitigchi** [comment]
You're welcome. Any feedback about the points I've mentioned above?

**Comment by 1024jp** [comment]
> Any feedback about the points I've mentioned above?

Where did you leave your comment? I couldn't find it.

**Comment by bitigchi** [comment]
I've left inline comments through Github, on `WindowPane.strings` and `Localizable.strings`, lines 45 and 741.

**Comment by 1024jp** [comment]
> I've left inline comments through Github, on `WindowPane.strings` and `Localizable.strings`, lines 45 and 741.

Really sorry, but could you point out where they are or just repeat them here? I could not find it (the review system in GitHub is truly complex.

**Comment by bitigchi** [comment]
No problem.

```
"zgz-Vf-91b.title" = "Draw separator";  // FIXME: new
"zgz-Vf-91b.title" = "Ayırıcıyı çiz";
```

Is it about drawing "the separator"?

```
"Change options" = "Change options";  // FIXME: new
"Change options" = "Seçenekleri değiştir";
```

Likewise, is this about changing the "options" or about something like "change" options?

**Comment by 1024jp** [comment]
Thank you.

> Is it about drawing "the separator"?

Yes, this is a new option to draw a separator between the line number view and the editor.

Screen Shot 2022-08-02 at 12 52 36


> Likewise, is this about changing the "options" or about something like "change" options?

This is the tooltip for a button (with the gear icon) to show the option setting view. That is, to be more precise, it doesn't "change" options but "show" options. So, now I think the tooltip should be "Show options" rather than the current "Change options". Could you also change the key string (only for it in tr.lproj is enough) to "Show options"?

Screen Shot 2022-08-02 at 12 53 25

Screen Shot 2022-08-02 at 12 53 38

**Comment by bitigchi** [comment]
Thanks for the detailed explanations! Updated accordingly.

**Pull request merged**
