### PR TITLE
Improve chinese localization

### PR DESCRIPTION
**Pull request by yylyyl**
Use standard terms from Apple.

https://support.apple.com/zh-hk/guide/terminal/apdd100908f-06b3-4e63-8a87-32e71241bab4/mac
https://support.apple.com/zh-cn/guide/terminal/apdd100908f-06b3-4e63-8a87-32e71241bab4/mac

### CODE REVIEW

**Comment by 1024jp** [comment]
Thank you for the PR.
Because I'm not a Chinese native, I'd like to ask @onevcat and @ShikiSuen before merging whether this change is reasonable. What do you think, guys?
The localization policy on CotEditor is not need to be a word-for-word translation but uses Apple-favored expressions if exist; otherwise, I'll just obey the decision by our localization maintainers.

This may relate to issue #1186 (Sorry, I've just left it for a long time).

**Comment by ShikiSuen** [comment]
異存なし。そのままにしておきましょう。
(I agree with this PR.)

**Comment by ShikiSuen** [comment]
@yylyyl Next time please use zh-TW sources, unless you want to derive a zh-HK translation set for CotEditor.
(Apple sometimes use different tranlations between zh-Hant-HK and zh-Hant-TW).

**Comment by yylyyl** [comment]
> @yylyyl Next time please use zh-TW sources, unless you want to derive a zh-HK translation set for CotEditor.
> (Apple sometimes uses different tranlations between zh-Hant-HK and zh-Hant-TW).

No problem.

Thank you everyone!

**Comment by 1024jp** [comment]
Thank you @onevcat and @ShikiSuen for the review!
I merged this.

**Pull request merged**
