### PR TITLE
fix some bug

### PR DESCRIPTION
**Pull request by coderyi**

### CODE REVIEW

**Comment by 1024jp** [comment]
1. Please make pull-request for each topic separately.
    - In this case, one for about the rtf document, one for about the notification center, and one for NS_DESIGNATED_INITIALIZER. 
2. Could you explain me what kind of issue exists in relation to the notification center registration and why it will be solved by this PR. I'm not sure, why you added `removeOberser:` methods for objects which did not registered as observer.
3. Thanks to your PR, I realized the Chinese AppleScript.rtf and Acknowledgements.rtf have several unlocalized sentences to be fixed. However, Your modification changed not only the sentence in the files but also Rich Text format a lots. Thus, it's not acceptable.
4. Just adding `NS_DESIGNATED_INITIALIZER` causes other confection. If we add `NS_DESIGNATED_INITIALIZER` to NSWindowController subclass, we also need to work overriding other initializer methods.

**Comment by coderyi** [comment]
notification center  and translate to Chinese

about notification center because  they  use postNotification or addObserver  ，so i think  when their object is dealloc,they will remove

when you use some init method，NS_DESIGNATED_INITIALIZER is a designated initializer,if not ,will warning. and then you CESyntaxMappingConflictsSheetController only one,i remove

and about rtf i revert,and i found AppleScript.rtf always have a big change,so i give up,about rtf, i suggest use plain text ,not rtf.then i commit again.

i feel embarrassed, i am so sorry

**Comment by 1024jp** [comment]
## removing notification's observer

You don't need to call `removeObserver:` when the object just posted notification in its lifetime.
`removeObserver:` is a pair to `addObserver` series. Posting notification isn't held by `[NSNotifiationCenter defaultCenter]`.

And you also don't need to remove observer at `dealloc` in CEScriptManager class since the observer of `addObserverForName:object:queue:usingBlock:` in `runShellScript:` is already removed in the block passed to the method.


## designated initializer of CESyntaxMappingConflictsSheetController

I didn't set `NS_DESIGNATED_INITIALIZER ` to `CESyntaxMappingConflictsSheetController`'s initializer  just because I'm lazy. It's actually totally ok by Objective-C+Cocoa not to set NS_DESIGNATED_INITIALIZER even it works as a designated initializer practically. Well, I'll set it at a later point in the future.


## rtf things

I will not change them to plain-text only to make development easier. Such documents are for end users. So they should be *readable* and formatted for human.

If you not familiar with rich text format, could you just translate them and comment them here as text? Then I'm going to put them into rtf documents. In addition to the sentences you localized, there are yet several unlocalized sentences at the end of AppleScript.rtf. It's very helpful for us if you also translate them to Chinese.


> i feel embarrassed, i am so sorry

Don't be sorry. You pointed out me what we passed by. Just one advice for the future is make topic branch for each issue when you make pull-request.

**Comment by coderyi** [comment]
okay ，i translate  several unlocalized sentences at the end of AppleScript.rtf。  thank you for your reply

**Comment by coderyi** [comment]
and i revert  my removeoberserver code

**Comment by 1024jp** [comment]
Oh, but, it seems your modification doesn't work.

screen shot 2015-10-20 at 17 15 56 1

Please just comment the sentences you localized as plain-text here this issue.

And...

1. You need to insert a space between Chinese character and roman alphabet.
    - e.g. `下面的一些新命令行增加到了‘selection’ 对象` to `下面的一些新命令行增加到了 ‘selection’ 对象`

**Comment by coderyi** [comment]
Acknowledgements.rtf

- Thanks to NSString+Sandboxing category by Ivan Vasic, which is distributed on https://gist.github.com/ivasic/4702892.

- 感谢Ivan Vasic的NSString+Sandboxing,它发布在https://gist.github.com/ivasic/4702892.


AppleScript.rtf
Selected line editing
The following new commands were added to the ‘selection’ object.
编辑选中行
下面的一些新命令行增加到了‘selection’ 对象.

move line up = Swap selected lines with the line just above. new on CotEditor 2.3.0
# Works only for ‘selection’ objects.


move line down = Swap selected lines with the line just below. new on CotEditor 2.3.0
# Works only for ‘selection’ objects.


sort lines = Sort selected lines ascending. new on CotEditor 2.3.0
# Works only for ‘selection’ objects.

reverse lines = Reverse selected lines. new on CotEditor 2.3.0
# Works only for ‘selection’ objects.


delete duplicate line = Delete duplicate lines in selection. new on CotEditor 2.3.0
# Works only for ‘selection’ objects.



move line up = 与选定行的上一行交换. CotEditor 2.3.0 新增
# 只对 ‘selection’ 对象有效.


move line down = 与选定行的下一行交换. CotEditor 2.3.0 新增
# 只对 ‘selection’ 对象有效.


sort lines = 对选定的行升序排列. CotEditor 2.3.0 新增
# 只对 ‘selection’ 对象有效.

reverse lines = 反转选定行. CotEditor 2.3.0 新增
# 只对 ‘selection’ 对象有效.


delete duplicate line = 删除选中内容的重复行. CotEditor 2.3.0 新增
# 只对 ‘selection’ 对象有效.

**Comment by coderyi** [comment]
you can close this

**Comment by 1024jp** [comment]
Thanks a lot! I've just added your localization to our documents🐈

**Pull request closed without merging**
