### PR TITLE
i18n@cp950 // Nomenclature fix to CotEditor 4.2.1.

### PR DESCRIPTION
**Pull request by ShikiSuen**
4.2.1 のおかげで、（zh-Hant 翻訳についての）訂正する必要のあるところは より安く見えるようになりました。
故にこの訂正用PRです。
よろしくお願い致します。

### CODE REVIEW

**Comment by ShikiSuen** [comment]
I decided to translate the word "document (文件)" as "file (檔案)".
I assume that CotEditor is a text file editor (not a document editor), hence this change.
This unites the written expression in the entire GUI so it won't confuse users anymore.

**Comment by 1024jp** [comment]
> I decided to translate the word "document (文件)" as "file (檔案)".
> I assume that CotEditor is a text file editor (not a document editor), hence this change.

That can not be applied to our case. The term “document” in the Apple universe has its own meaning and the thing CotEditor handles is exactly the “document” in this context. You can refer to the [Apple Style Guide](https://help.apple.com/applestyleguide/#/apsg1eef9171) to understand how Apple uses (English) terms in their products & materials.

Screen Shot 2022-05-11 at 15 07 03


According to the [Apple Localization Terms Glossary for macOS](https://applelocalization.com/macos?q=document&l=English&l=Japanese&l=Traditional+Chinese), Apple consistently uses “文件” for the term “document” in traditional Chinese. So CotEditor should also follow it.


> ちなみにですが、
>
> ```
> /* Class = "NSTextFieldCell"; title = "Document File"; ObjectID = "5tP-OA-Ujw"; */
> ```
> その英語タイトルは「File Information」と変更すればいかがなさいましょうか。

Nevertheless, your suggestion here sounds good. So, let's make it not “File Information” but “Document Information”. I'll push a commit later.

**Comment by 1024jp** [comment]
FYI, you can build CotEditor on this repo even if you don't set up the iCloud things. Refer to [Build for Ad-hoc usage in README.m](https://github.com/coteditor/CotEditor#build-for-ad-hoc-usage).

**Comment by 1024jp** [comment]
> Nevertheless, your suggestion here sounds good. So, let's make it not “File Information” but “Document Information”. I'll push a commit later.

Ooops, ignore my reply above. I did not care where this line locates. Now I think “File Information" is better in this case especially. Maybe. Let me have time later just because I'm now outside.

**Comment by ShikiSuen** [comment]
@1024jp I'll wait until you finish updating your English strings.

**Comment by 1024jp** [comment]
@ShikiSuen Hi. I slept on it and ended up not changing the line "Document File". Now I believe the current one is the best among the candidates. 
The word "information" is not essential because it's obvious that there is something information in an inspector. So just "File" can also be a candidate but "Document File" explains better it is about the file of *this document*.

**Comment by ShikiSuen** [comment]
@1024jp Then the issue is that the direct translation of "Document File" in both Simplified Chinese (文档文件) and Traditional Chinese (文件檔案) are hijoushiki to native Chinese speakers, feeling like saying a similar word twice.

Please let me know if you still think it is important to enforce the Chinese translation in this way.

**Comment by 1024jp** [comment]
> Then the issue is that the direct translation of "Document File" in both Simplified Chinese (文档文件) and Traditional Chinese (文件檔案) are hijoushiki to native Chinese speakers, feeling like saying a similar word twice.

I believe it is totally ok because Apple uses the term "文件檔案" in multiple places.
cf. [Apple Localization Terms Glossary for macOS](https://applelocalization.com/macos?q=document+file&l=English&l=Simplified+Chinese&l=Traditional+Chinese)

Especially, TextEdit.app also uses it. So, we should use the same term for the same object.

**Comment by ShikiSuen** [comment]
@1024jp Copy that. It just looks really uncomfortable to Windows users.

I'll fix this tonight.

**Comment by 1024jp** [comment]
> It just looks really uncomfortable to Windows users.

CotEditor is an application only for macOS. Different platforms have different manners. We should use macOS terminology.

> I'll fix this tonight.

Thank you. I'll merge after the update.

**Comment by ShikiSuen** [comment]
@1024jp I finished fixing the translation of the word "Document".
BTW I still failed from compiling even after following the instructions written in the README.MD file:
image

**Comment by 1024jp** [comment]
Thank you!

> BTW I still failed from compiling even after following the instructions written in the README.MD file:

Hmm, it looks like the compiler doesn't understand Swift 5.6. To build CotEditor, you need Xcode 13.3, which is available only on macOS 12.

**Comment by ShikiSuen** [comment]
@1024jp Xcode 13.3 is extremely buggy on my mac mini 2018 when handling projects mixed with Swift and ObjCpp.

Xcode 13.2.1 is pretty stable for developing vChewing input method. However, I just got rid of all Cpp-written components and it becomes a Swift-only project. I guess it's about time to upgrade to Xcode 13.3 again.

**Pull request merged**
