### PR TITLE
Add syntax highlightning for PRQL

### PR DESCRIPTION
**Pull request by vanillajonathan**
PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.

https://prql-lang.org/
https://github.com/PRQL/prql

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@1024jp Could you merge this?

**Comment by vanillajonathan** [comment]
@1024jp ping!

**Comment by 1024jp** [comment]
Sorry for taking time make a dicision.

CotEditor has a policy of bundling only the syntaxes of widely used languages.
And PRQL does not seem to have reached that level yet.
It would be better to share it separately for the users who need this format.

I appriciate trying to contribute to our project.

**Comment by vanillajonathan** [comment]
Maybe you can add instructions to the website and/or the wiki on how users can install syntax files that are not bundled with CotEditor?

Maybe the preferences dialog could have a link that points to the additional syntax highlighting article in the wiki to make it easier for users to discover that can install additional syntax highlighting files and where to find them.

**Comment by 1024jp** [comment]
We already have such instructions in the bundled user guide.

Screenshot 2024-06-04 at 8 26 22

Moreover, there is also a link to the list of additional syntaxes in our web page.  

https://coteditor.com/archives

**Pull request closed without merging**
