### PR TITLE
Initial pt localization.

### PR DESCRIPTION
**Pull request by vitu**
Issues:

1) Layout - Preferences > Window > Get from Sample Window 
layout1

2) Layout - Preferences > Window
layout2

3) Layout - Preferences > Appearance
layout3

4) Layout - File > Print
layout4

5) Layout - Preferences > Format, select a style and, in the gear icon, select Show File Mapping Conflicts…
layout5

6) Layout - Preferences > Format, select a style and select the pencil icon
layout6

7) Missing string; not found for localization - Window > Panel
missing string

8) Tooltip from other source - Font menu bar icon shows a tooltip that is inconsistent with other menu bar tooltips; not found for localization
tooltip from other source

### CODE REVIEW

**Comment by 1024jp** [comment]
Thank you for the pull-request.
Looks nice.
I'd like to merge this first, adjust Autolayout things, and then let you know about additional work.

I also have some questions about this localization.
So, I'll email you later.

**Comment by 1024jp** [comment]
Before I compose an email, I answer the issues you mentioned. 

All of 1.-6. were resolved in the latest develop branch. Thanks.

> 7. Missing string; not found for localization - Window > Panel

The Panel submenu was omitted on CotEditor 3.3. So. you don't need to localize it.

> 8. Tooltip from other source - Font menu bar icon shows a tooltip that is inconsistent with other menu bar tooltips; not found for localization

The tooltips and labels of toolbar Font icon are automatically generated by the system. So we cannot customize it.


In addition, I've updated some localization to conform to the Apple standard.

1. I omitted the parentheses from "espaços." This is how Apple treats the plural. c.f. ScriptEditor.app

screen shot 2018-01-18 at 16 18 15

2. I inserted spaces around "/" for "macOS / Unix".

screen shot 2018-01-18 at 16 21 47

**Comment by vitu** [comment]
Thanks a lot for all the layout fixes and info. Regarding your updates:

1. The idea here was to make it grammatically right for singular as well. If you opt to have it this way, could you please remove the parenthesis from the below for consistency?

String ID:  		36
Note:        		/* Class = &quot;NSTextFieldCell&quot;; title = &quot;times&quot;; ObjectID = &quot;VLD-jj-zzl&quot;; */
English:     		times
Translation:		vez(es)
Locale:      		pt_BR
====================

2. The idea here was to use spacing around slashes as they normally appear in target language. If you opt to have it this way, could you please add spaces to the below for consistency?

String ID:  		40
Note:        		/* Class = &quot;NSMenuItem&quot;; title = &quot;CR / LF&quot;; ObjectID = &quot;Zo1-Cc-YBm&quot;; */
English:     		CR / LF
Translation:		CR/LF
Locale:      		pt_BR

====================

String ID:  		3
Note:        		/* Class = &quot;NSMenuItem&quot;; title = &quot;macOS / Unix (LF)&quot;; ObjectID = &quot;15&quot;; */
English:     		macOS / Unix (LF)
Translation:		macOS/Unix (LF)
Locale:      		pt_BR
====================

String ID:  		63
Note:        		/* Class = &quot;NSToolbarItem&quot;; paletteLabel = &quot;Show / Hide Invisibles&quot;; ObjectID = &quot;xbD-Up-YfQ&quot;; */
English:     		Show / Hide Invisibles
Translation:		Mostrar/Ocultar Invisíveis
Locale:      		pt_BR

====================

String ID:  		18
Note:        		/* Class = &quot;NSToolbarItem&quot;; paletteLabel = &quot;Show / Hide Page Guide&quot;; ObjectID = &quot;GS6-aA-mgz&quot;; */
English:     		Show / Hide Page Guide
Translation:		Mostrar/Ocultar Guia da Página
Locale:      		pt_BR

**Comment by 1024jp** [comment]
I tweaked the spaces and the parentheses since I found that Apple does in the the same way in Script Editor.app.
In addition, the current CR/LF will be changed to CRLF in 3.3.0 also to fit to the Apple’s favor. 
CotEditor, or a Cocoa app, should behave like Apple as possible.

Regarding toolbar items, I’ve just found Apple doesn’t insert spaces around “/“ (e.g. in Safari).
So, it seems I need to remove them. I’ll do it later.

**Pull request merged**
